version: "3.8"
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: db
    ports:
      - "5433:5432"
